### ISSUE TITLE
Non 201 status code during passive scan request to burpbuddy

### ISSUE THREAD

**Issue by Etraud123** [tomsteele/burpstaticscan#4]
I've been using your tool for a while now, and when i scan a folder it gives me this error:

Non 201 status code during passive scan request to burpbuddy

But, when i do with different code if gives ok, and the instance of burpbuddy its the same, is there any limitation to the burpbuddy that i'm not aware off?

**Comment by tomsteele** [comment]
Hi @Etraud123, you're saying when you send a POST to `/scan/passive` in different code you get a non 201 response?

**Comment by tomsteele** [comment]
Going to close this as I haven't heard back from you yet. Feel free to re-open if you have more details :)
